### ISSUE TITLE
error: patch failed: libavformat/movenc.c:6606

### ISSUE THREAD

**Issue by xrealm** [unifiedstreaming/live-demo-cmaf#10]
#8 0.299 Cloning into '.'...
#8 180.9 error: patch failed: libavformat/movenc.c:6606
#8 180.9 error: libavformat/movenc.c: patch does not apply

**Comment by jamie-usp** [comment]
Fixed in https://github.com/unifiedstreaming/live-demo-cmaf/commit/8cb784e698426e2265cf143a14d404f0df895e7d
