### ISSUE TITLE
sidx box not present when --global_sidx used. 

### ISSUE THREAD

**Issue by jamie-usp** [unifiedstreaming/live-demo-cmaf#3]
When -global_sidxis enabled with the MP4 muxer, no sidx is present in the file. Notes on this feature indicate a box should be present Write global SIDX atom. Applicable only for single file, mp4 output, non-streaming mode.

**Comment by jeeb** [comment]
For the record, you can check the options registered for a given muxer with `-h muxer=FORMAT` (in this case two of interest being `dash` and `mp4`).

You will notice that the mp4 muxer has `global_sidx` as well as `skip_sidx` as flags for the `movflags` option.

Meanwhile, later the DASH meta-muxer author chose to map an option `global_sidx`, which then internally for the mp4 muxer sets the matching `movflags` flag. So it is just a case of difference between modules.
