### ISSUE TITLE
Interface 2 - Video tracks contain no bitrate information

### ISSUE THREAD

**Issue by jamie-usp** [unifiedstreaming/live-demo-cmaf#5]
Unified Origin requires the presence of a bitrate to be signaled in the btrt box for video tracks. Currently this issue only affect the Interface 2 (dash/hls) demo. 

Need raising/escalating to FFlabs.

**Comment by jeeb** [comment]
`btrt` box was implemented in http://git.videolan.org/?p=ffmpeg.git;a=commit;h=3838e8fc210aa09a9f9058506c0ce80b6ad9b9c3 .

**Comment by jamie-usp** [comment]
Thanks again @jeeb 

once again, confirmed and tested with commit: https://github.com/unifiedstreaming/live-demo-cmaf/commit/65a7fbe7d5a92878690e853a26b2b5d1414f246b
